PAN-81: Setting order of blog articles on category or tag edit pages
astrogoat/blog pull request #15
Opened 2023-05-05 11:11 UTC by garos4

2023-05-08 14:18 UTC, BaffourAdu commented on src/Models/Category.php
> +        // return $this->belongsToMany(Article::class, 'blog_category_blog_article')
@garos4 yo left comments in here

2023-05-08 14:18 UTC, BaffourAdu commented on public/css/blog.css
> +.blog-sr-only {
I am a little confused as to why this file was committed

2023-05-11 10:26 UTC, tonning requested changes

2023-05-11 10:26 UTC, tonning commented on yarn.lock
We use Yarn. And there should already be a `package-lock.json` file committed. Can you please remove this file.

2023-05-11 10:26 UTC, tonning commented on database/migrations/2023_05_01_000000_add_order_column_to_blog_article_table.php
> +            $table->integer('order');
For consistency, let's add this row before the timestamps instead of after them.

```suggestion
            $table->integer('order')->after('slug');
```

2023-05-11 10:26 UTC, tonning commented on database/migrations/2023_05_01_000000_add_order_column_to_blog_article_table.php
> +            $table->integer('order');
How do we want to address current articles that doesn't have an order value set yet?

2023-05-11 11:20 UTC, garos4 commented on database/migrations/2023_05_01_000000_add_order_column_to_blog_article_table.php
> +            $table->integer('order');
@tonning Current articles that don't have orders, that is, the `order` field is `NULL`, are by default sorted in ascending order by the order in which they were created.

2023-06-12 14:55 UTC, tonning approved these changes

2023-06-12 14:55 UTC, merged