Add trending posts control
astrogoat/blog pull request #9
Opened 2022-08-03 11:11 UTC by OniiCoder

2022-08-03 11:19 UTC, iamkarsoft approved these changes
awesome work!

2022-08-03 11:37 UTC, garos4 approved these changes

2022-08-05 14:30 UTC, BaffourAdu requested changes

2022-08-05 14:30 UTC, BaffourAdu commented on src/Models/Group.php
> +//        return route('lego.blog.group.editor', [
@OniiCoder forgot to remove comments here

2022-08-05 14:42 UTC, OniiCoder commented on src/Models/Group.php
> +//        return route('lego.blog.group.editor', [
@BaffourAdu function is required to be implemented but content is not necessary as I am not using the editor for the model.

2022-08-08 14:05 UTC, bmmage approved these changes
Looks good, great work! I've added two comments around some code comments 😅 . Throwing an approval on this since those comments are more cosmetic than functional.

2022-08-08 14:05 UTC, bmmage commented on src/Http/Livewire/Models/TagForm.php
> +//    protected $listeners = [
Can you remove this commented code?

2022-08-08 14:05 UTC, bmmage commented on src/Models/Tag.php
> +//            'tag' => $this,
I'd seen the discussion between you and BaffourAdu on this. I'd recommend removing the current comment and possibly put a 'unused' type comment just for clarity.

2022-08-19 12:47 UTC, garos4 approved these changes

2022-08-22 16:10 UTC, bmmage commented on src/Models/Tag.php
> +    protected $table = 'article_tags';
Would it be worth making the 'tags' more generic and part of strata proper so we could tag other models in the future?

2022-09-12 13:04 UTC, tonning approved these changes

2022-09-12 13:05 UTC, merged